# Generated by Django 3.1.7 on 2021-12-04 16:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_club', models.CharField(max_length=30)),
                ('short_name', models.CharField(max_length=5)),
            ],
            options={
                'ordering': ('ligue__nom_ligue', 'short_name'),
            },
        ),
        migrations.CreateModel(
            name='Ligue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ligue', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('nom_ligue',),
            },
        ),
        migrations.CreateModel(
            name='ModeJeux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_jeux', models.CharField(blank=True, max_length=30, null=True, verbose_name='Mode de jeu')),
                ('color', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Mode de Jeux',
            },
        ),
        migrations.CreateModel(
            name='TourDeJeu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_nbr', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tour N°')),
                ('nbr_maxi_joueur', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nombre maxi de joueur')),
                ('nbr_inscrit', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Nombre d'inscrit")),
                ('nbr_inscrit_att', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Nombre d'inscrit sur liste d'attente")),
                ('date', models.DateField()),
                ('lieu_organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tournoi.club')),
                ('mode_jeu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tournoi.modejeux', verbose_name='Mode de jeu')),
            ],
            options={
                'verbose_name_plural': 'Tour de Jeux',
                'ordering': ('date', 'lieu_organisation__short_name'),
            },
        ),
        migrations.CreateModel(
            name='ListJoueur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('joueur_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tourdejeu_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tournoi.tourdejeu')),
            ],
            options={
                'verbose_name_plural': 'Liste des joueurs par tournoi',
                'ordering': ('date',),
            },
        ),
        migrations.AddField(
            model_name='club',
            name='ligue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tournoi.ligue'),
        ),
    ]
