# Generated by Django 3.1.7 on 2021-12-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournoi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourdejeu',
            name='nbr_inscrit',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name="Nombre d'inscrit"),
        ),
    ]
