# Generated by Django 3.1.7 on 2021-12-05 06:35

from django.db import migrations, models
import django.db.models.deletion
import tournoi.models


class Migration(migrations.Migration):

    dependencies = [
        ('tournoi', '0002_auto_20211204_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourdejeu',
            name='mode_jeu',
            field=models.ForeignKey(blank=True, default=tournoi.models.ModeJeux.get_default_pk, null=True, on_delete=django.db.models.deletion.PROTECT, to='tournoi.modejeux', verbose_name='Mode de jeu'),
        ),
        migrations.AlterField(
            model_name='tourdejeu',
            name='nbr_inscrit_att',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name="Nombre d'inscrit sur liste d'attente"),
        ),
        migrations.AlterField(
            model_name='tourdejeu',
            name='nbr_maxi_joueur',
            field=models.PositiveSmallIntegerField(blank=True, default=8, null=True, verbose_name='Nombre maxi de joueur'),
        ),
    ]
