# Generated by Django 3.1.7 on 2021-12-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournoi', '0003_auto_20211205_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='listjoueur',
            name='list_att',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
