# Generated by Django 3.1.7 on 2021-12-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournoi', '0004_listjoueur_list_att'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listjoueur',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
