# Generated by Django 3.2.6 on 2021-12-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournoi', '0006_auto_20211210_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourdejeu',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
