# Generated by Django 3.2.6 on 2021-12-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournoi', '0007_alter_tourdejeu_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourdejeu',
            name='date',
            field=models.DateField(),
        ),
    ]
